import { Jost, Vollkorn } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header";


const vollkorn = Vollkorn({
  variable: "--font-vollkorn",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Safwan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
       className={`${jost.variable} ${vollkorn.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}
      </body>
    </html>
  );
}
